apiVersion: v1
kind: Service
metadata:
  name: employee-producer-sesrvice
spec:
  selector:
    app: pod
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30021
  type: NodePort   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-producer
  labels:
    app: employee-producer-node-deployement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
      - name: employee-producer-microservice
        image: dockersiva777/employee-producer
        ports:
        - containerPort: 8080
